django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

django_app/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_app/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField('질문내용', max_length=200)
    pub_date = models.DateTimeField('발행일자')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = '최근 발행 여부'


class Choice(models.Model):
    question = models.ForeignKey(
        Question,
        verbose_name='해당질문',
        on_delete=models.CASCADE
    )
    choice_text = models.CharField('선택내용', max_length=200)
    votes = models.IntegerField('총 투표수', default=0)

    def __str__(self):
        return self.choice_text

django_app/polls/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse

from .models import Question, Choice


def index(request):
    # get_list_or404를 사용한 경우
    latest_question_list = get_list_or_404(
        Question.objects.order_by('-pub_date')[:5]
    )
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    # question_id 가 pk인 Question 객체를 가저와
    # context라는 이름을 가진 dict에 'question'이라는 키 값으로 위 변수를 할당
    # 이 후 'polls/detail.html'과 context를 랜더한 결과를 리턴

    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    # detail.html 파일을 수정해서 result.html을 만들고
    # 질문에 대한 모든 선택사항의 선택수(votes)를 출력
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    # detail.html 내부
    #   question을 출력
    #   해당 question의 모든 choice를 (question.choice_set.all) 출력
    #   loop돌며 각 choice의 제목과 votes를 출력
    return render(request, 'polls/result.html', context)


def vote(request, question_id):
    # request의 method가 POST 방식일 때
    if request.method == 'POST':
        # 전달받은 데이터 중 'choice'키에 해당하는 값을
        # HttpResponse에 적절히 돌려준다
        data = request.POST
        try:
            choice_id = data['choice']
            # choice 키에 해당하는 Choice 인스턴스의 vote값을 1증가 시키고
            # 데이터베이스에 변경사항을 반영
            choice = Choice.objects.get(id=choice_id)
            choice.votes += 1
            choice.save()
            return redirect('polls:results', question_id)
        except (KeyError, Choice.DoesNotExist):
            # message프레임워크를 사용
            # 지금 모르셔도 됩니다
            # request에 메시지를 저장해 놓고 해당 request에 대한
            # reponse를 돌려줄 때 메시지를 담아 보낸다
            messages.add_message(
                request,
                messages.ERROR,
                "You didn't select a choice",
            )
            return redirect('polls:detail', question_id)
            # 이 후 return   페이지로 redirect
    else:
        return HttpResponse("You're voting on question %s." % question_id)

django_app/templates/polls/base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <title>{% block title %}Polls Application{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

django_app/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>
    {% if messages %}
        {% for message in messages %}
            <p><strong>{{ message }}</strong></p>
        {% endfor %}
    {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio"
           name="choice"
           id="choice-{{forloop.counter}}"
           value="{{ choice.id }}">
    <label for="choice-{{ forlooop.counter }}">
        {{ choice.choice_text }}
    </label><br/>
    {% endfor %}
    <button type="submit">Vote</button>
    <!--<input type="submit" value="Vote">-->
</form>

{% endblock %}

django_app/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>Polls Application</h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question_id=question.pk %}">
        {{ question.question_text }}
    </a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

django_app/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>
    {% if messages %}
    {% for message in messages %}
<p><strong>{{ message }}</strong></p>
    {% endfor %}
    {% endif %}
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        <span>{{ choice.choice_text }}:{{ choice.votes }}번</span>
    </li>
    {% endfor %}

    <a href="{% url 'polls:detail' question.id%}">Vote again</a>
</ul>

{% endblock %}

django_app/templates/polls/results.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>